services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: challengers_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_ENV=local
      - DB_CONNECTION=sqlite
